经常在while-try-except 中遗忘 break, 导致即使捕获异常也无法终结while
而且遇到此种情况，还常常跑到其他地方找错 --|||


