>>> def f():
...     try:
...         break
...     finally:
...         print 'finally'
... 
  File "<stdin>", line 3
SyntaxError: 'break' outside loop

